name: Actualizar datos AVAL

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuta todos los días a las 12:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install --upgrade yfinance pandas

    - name: Ejecutar colector
      run: |
        python src/collector.py

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Hacer commit y push de los cambios
      run: |
        git add src/static/historical.csv log_data.csv
        git commit -m "Actualización automática de datos AVAL"
        git push https://github.com/${{ github.repository }} HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}