name: Actualizar datos AVAL

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuta todos los días a las 12:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Paso 1.) Checkout del repositorio
      uses: actions/checkout@v3

    - name: Paso 2.) Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Paso 3.) Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install .  # Instala el paquete desde el setup.py (en la raíz del proyecto)

    - name: Paso 4.) Ejecutar colector
      run: |
        python src/collector.py

    - name: Paso 5.) Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Paso 6.) Hacer commit y push de los cambios
      run: |
        git add src/static/historical.csv src/logs/log_data.csv src/logs/text_logs/log_data.log
        git commit -m "Actualización automática de datos AVAL"
        git push https://github.com/${{ github.repository }} HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}